### ISSUE TITLE
Incorrect Scroll map 

### ISSUE THREAD

**Issue by neerajanand321** [cooelf/Auto-GUI#13]
Hi, Thanks for the nice work. I think in utils_data, co-ordinates for left and right are wrong, for left instead of [[0.8000, 0.5000], [0.2000, 0.5000]] it should be [[0.5, 0.8], [0.5, 0.2]] and for right it should be [[0.5, 0.2], [0.5, 0.8]]

**Comment by cooelf** [comment]
Yes. There is a mistake in the old script. It does not align with the latest version of the paper (which has fixed the coordinates). We have just updated the script. Thanks.
